server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
    gateway:
      routes:
        - id: orderService #路由标识,唯一
          uri: lb://orderService #路由地址
          predicates: #断言,路径匹配规则
            - Path=/order/**
          filters: #路由过滤器
            - AddRequestHeader=Cookie,123
        - id: userService #路由标识,唯一
          uri: lb://userService #路由地址
          predicates: #断言,路径匹配规则
            - Path=/user/**
      default-filters: #全局路由过滤器
        - AddRequestHeader=token,456
